### ISSUE TITLE
Feature request: RecognitionConfig param partial_results

### ISSUE THREAD

**Issue by subnetsRU** [TinkoffCreditSystems/tinkoff-speech-api-examples#10]
It will be good to add to RecognitionConfig new param: partial_results (bool)

If true than voicekit will send partial results of recognition and not only end phase.

**Comment by penguin138** [comment]
You can use streaming recognition for this. There is StreamingRecognitionConfig which contains InterimResultsConfig where you can switch on enable_interim_results to true.

**Comment by subnetsRU** [comment]
Ok, thanks. How I didnt see that... sorry
