### ISSUE TITLE
annotations.proto was not found

### ISSUE THREAD

**Issue by annabali** [TinkoffCreditSystems/tinkoff-speech-api-examples#12]
Добрый день!
Хотела запустить примеры, но проблемы возникли на этапе настройки.
После установки requirements.txt попыталась сгенерить protobuf командой ./sh/generate_protobuf.sh, но вылезла ошибка.
В чем может быть проблема?
```
google/api/annotations.proto: File not found.
apis/stt.proto:6:1:  Import "google/api/annotations.proto" was not found or had errors.
```

**Comment by standy66** [comment]
Надо склонировать с флагом `--recursive` либо в уже существующем репо сделать `git submodule init && git submodule update`

**Comment by standy66** [comment]
Пофикшено в новой версии примеров.
