### ISSUE TITLE
Cannot infer VOICEKIT_API_KEY

### ISSUE THREAD

**Issue by annabali** [TinkoffCreditSystems/tinkoff-speech-api-examples#14]
Добрый день!
Ошибка: 
recognize.py: error: Cannot infer VOICEKIT_API_KEY, pass via --api_key command line parameter or VOICEKIT_API_KEY environment variable 
в чем может быть проблема? 
сделано всё по инструкции
установлены export VOICEKIT_API_KEY="Your API key"
export VOICEKIT_SECRET_KEY="Your secret key"
затем уже вызвана команда python3 recognize.py -r 16000 -c 1 -e MPEG_AUDIO ../audio/sample_1.mp3

**Comment by standy66** [comment]
Нужно вместо Your API key и Your secret key вставить настоящие ключи)

**Comment by annabali** [comment]
> Нужно вместо Your API key и Your secret key вставить настоящие ключи)

Были вставлены настоящие ключи, которые прислали для пробы

**Comment by standy66** [comment]
Странно, ошибка говорит о том, что из переменной VOICEKIT_API_KEY не удалось достать. Попробуйте задать в командной строке через --api_key и --secret_key

**Comment by vadimkantorov** [comment]
@standy66 Проблема в том, что парсер аргументов CommonParser падает уже при попытке задать дефолтовые значения для `--api_key` и `--secret_key`, не доходя собственно до обработки переданных значений.

https://github.com/TinkoffCreditSystems/voicekit-examples/blob/master/python/common.py#L116-L122

Wokarounds:
1) заменить эти строчки на
```
@property
    def _default_api_key(self):
        return '' #self._get_key("VOICEKIT_API_KEY", "STT_TEST_API_KEY", "api_key")

    @property
    def _default_secret_key(self):
        return '' #self._get_key("VOICEKIT_SECRET_KEY", "STT_TEST_SECRET_KEY", "secret_key")
```
2) передавать значения ключей через переменные окружения
