### ISSUE TITLE
How to turn on the female voice in synthesis?

### ISSUE THREAD

**Issue by skokov2006** [TinkoffCreditSystems/tinkoff-speech-api-examples#24]
Good afternoon!

I use text-to-speech via Node js. Constantly generated synthesis by the male voice. Can you please tell us how to switch to a female voice?

**Comment by fsatka** [comment]
Good morning!

You can find it in [updated proto files](https://github.com/TinkoffCreditSystems/voicekit-examples/blob/master/apis/tinkoff/cloud/tts/v1/tts.proto#L69).
