### ISSUE TITLE
STT: confidence and stability not normalized to 0...1

### ISSUE THREAD

**Issue by ishmakov** [TinkoffCreditSystems/tinkoff-speech-api-examples#3]
what units of measurement for results?

**Comment by standy66** [comment]
Hello!
They are logs of probabilities as returned by beam search decoder. The values are in range (-inf, 0].  If used in rescoring or some other decision-based pruning they should probably be normalized by utterance length in some form (length of audio in seconds, number of character in recognition result, etc)
