### ISSUE TITLE
NODEJS example

### ISSUE THREAD

**Issue by subnetsRU** [TinkoffCreditSystems/tinkoff-speech-api-examples#6]
It will be nice if someone push here example for NODEJS.

Thanks.

**Comment by penguin138** [comment]
Hi. Actually, we use [gRPC](https://grpc.io/docs/), so to use our API you only need these two files: python/apis/stt.proto and python/apis/tts.proto. From those files you can generate code in NodeJS using protoc and then write a client similar to one shown [here](https://grpc.io/docs/tutorials/basic/node/). Unfortunately, for now the only public reference examples on what methods to call and which parameters to use are in python, but we'll be adding general documentation and how to guides soon, we might also add examples in other languages.

**Comment by subnetsRU** [comment]
Thanks for the answer.

Ofc I understood that it is gRPC and I have first problem with understanding your auth. I don`t know python at all..

As example NODEJS code for Yandex (they use gRPC too) auth look like this:
```
    metadata = new grpc.Metadata();
    metadata.set('authorization', 'Bearer ' + config.yandex.token.iam);

    var sttProto = grpc.loadPackageDefinition(packageDefinition).yandex.cloud.ai.stt.v2;

    var sslCreds = grpc.credentials.createSsl();
    var client = new sttProto.SttService(config.yandex.host + ':' + config.yandex.port, sslCreds);
    var sttService = client.StreamingRecognize(metadata);

    //fist message send config for this session
    sttService.write(sttServiceConfig);

```
And than you can send audio data.

When I look at your python example I see func authorization_metadata that call func generate_jwt and still try to understand two things:
* how to gen auth data in JS
* when send config 

And for now my result:
```
tinkoff error: code 7 [7 PERMISSION_DENIED: ]
Error: 7 PERMISSION_DENIED: 
```

But OK, I understood. Will try to do it by myself.

**Comment by subnetsRU** [comment]
I have some success. Think I passed auth section. Because error changed to:
```
sttService connected
tinkoff error: code 1 [1 CANCELLED: (<class 'ValueError'>, ValueError('First streaming recognize request must contain streaming_config and must not contain audio_content.',), <traceback object at 0x7fb083cb5f88>)] (talk.js:173)
Error: 1 CANCELLED: (<class 'ValueError'>, ValueError('First streaming recognize request must contain streaming_config and must not contain audio_content.',), <traceback object at 0x7fb083cb5f88>)
```
And its the second question about config.

P.S. Maybe it will help someone -> functions for node will be look like this:
```
function generate_jwt(api_key, secret_key, payload){
    var crypto = require('crypto');
    expiration_time = 600;
    header = {
        "alg": "HS256",
        "typ": "JWT",
        "kid": api_key
    }

    payload['exp'] = parseInt(new Date().getTime()/1000) + expiration_time;
    payload_bytes = JSON.stringify(payload);
    header_bytes = JSON.stringify(header);
    
    data = (Buffer.from(header_bytes).toString('base64') + '.' + Buffer.from(payload_bytes).toString('base64'));
            
    b_secret_key = pad_base64(secret_key);
    decode_secret_key = new Buffer.from(pad_base64(secret_key), 'base64').toString('utf8');
    
    hmac = crypto.createHmac('sha256',decode_secret_key).update(data,'utf8').digest();
    signature = Buffer.from( hmac ).toString('base64');
        
    jwt = data + '.' + signature;
 return jwt;
}

function pad_base64(base64_str){
    len = base64_str.length;
    num_equals_signs = 4 - len % 4;

    if (num_equals_signs < 4){
        equals_signs = '';
        for(i=0;i<num_equals_signs;i++){
            equals_signs += '=';
        }
        return base64_str + equals_signs;
    }

 return base64_str;
}       
```
But I still dont get for what `expiration_time` is.

**Comment by subnetsRU** [comment]
Finnaly I got it.

Full streaming example for NodeJS can be found [here](https://github.com/subnetsRU/speechKit/tree/master/tinkoff)

**Comment by subnetsRU** [comment]
One more question.

Param expiration_time - what for ? What will happen after this time ?

**Comment by penguin138** [comment]
The token that you generate to access the service is a [JWT](https://jwt.io/introduction/) token. The expiration time or 'exp' is a standard field in JWT payload. It represents the moment in time when your token stops being accepted by the authorization service and you need to generate a new one. These tokens are meant to be short-lived so that no other party can access the service using your API key without you granting that access by generating a token using a pair of keys: API key and secret key. Also, this field is not mandatory, you can use either 'iat' or 'exp'. When using 'iat' the token will become invalid after 10 minutes. When using 'exp' you determine when your token should become invalid. We'll put the authorization description in the docs. Thanks for asking!

**Comment by subnetsRU** [comment]
Thanks for the reply.
