### ISSUE TITLE
Question: Audio format

### ISSUE THREAD

**Issue by subnetsRU** [TinkoffCreditSystems/tinkoff-speech-api-examples#8]
If audio format:
```
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```
[This file](https://github.com/subnetsRU/speechKit/blob/master/tinkoff/audio.pcm) that I used for example and with _RecognitionConfig_ config:
```
{ streaming_config:
   { config:
      { encoding: 'LINEAR16',
        sample_rate_hertz: 16000,
        language_code: 'ru-RU',
        max_alternatives: 4,
        num_channels: 1 } } }
```
I receive recognition responses.

Now convert this audio in another audio format:
```
Channels       : 1
Sample Rate    : 8000
Precision      : 16-bit
Bit Rate       : 128k
Sample Encoding: 16-bit Signed Integer PCM
```
In proto file stt.proto in _AudioEncoding_ there is ALAW. Set new _RecognitionConfig_ config:
```
{ streaming_config:
   { config:
      { encoding: 'ALAW',
        sample_rate_hertz: 8000,
        language_code: 'ru-RU',
        max_alternatives: 4,
        num_channels: 1 } } }
```
But no recognition responses at all...  

I tryied LINEAR16 8000 but same result...

What I`am doing wrong ?

**Comment by penguin138** [comment]
How did you convert your file to a-law? I did the following:
```
sox  -r 16k -c 1 audio.s16 -r 8k -c 1 audio_8khz.al
```
When I sent `audio_8khz.al`  I got all recognition responses from the server.
Also, A-law is actually 8-bit encoding, or did you also try to send 8 kHz linear PCM?

**Comment by subnetsRU** [comment]
Actually I dont convert anything. ALAW I tryied just for try, we all humans and we can make mistakes :)

I took WAV file that was recorder by Asterisk cmd Mixmonitor (16-bit Signed Integer PCM, mono, 8kHz). Than I did RAW (LPCM) from it - delete WAV header (first 44 bytes)  bc I use speechkit in the scheme: asterisk -> script -> speechkit -> script -> asterisk. So script sends Asterisk audio stream (Signed Linear PCM mono 8000) on the fly to the speechkit and wait for responces.

Than run my [test script](https://github.com/TinkoffCreditSystems/tinkoff-speech-api-examples/issues/6#issuecomment-517718454) with this RAW file and no recognition responses. 
I attach [example](https://github.com/TinkoffCreditSystems/tinkoff-speech-api-examples/files/3464644/example.zip) file, no recognition responses for it.

While writing this post decide to do online test. Write new file by myself - count from 1 to 10. Than do same (headless) and got recognition responses with config LINEAR16 8000. 
```
Channel 0
Phrase start { seconds: '5', nanos: 310000000 }
Phrase end { seconds: '7', nanos: 200000000 }
Is final true
Transcription раз два
Confidence -5.028108596801758
------------------
Transcription раз два 
Confidence -11.16067886352539
------------------
Transcription раз да
Confidence -11.821344375610352
------------------
=== RESPONSE END ===
and so on ...skiped...
```

Hmmm... I'm confused. Format of the files are the same, so maybe your voicekit just cant recognize this audio and its not format problem as I thought before.

**Comment by subnetsRU** [comment]
Может перейдем на русский ? :) Или будем продолжать по аглицки ?

**Comment by subnetsRU** [comment]
Прикрутил к скрипту на тестовом стенде, в черновом варианте, tinkoff voicekit. Позвонил, поговорил, работает. Результаты распознавания приходят.

Теперь я совсем не понимаю почему их нет, озвученном выше, примере.... похоже дело тут не в формате, а в чем то ином. Но в чем ? Это вопрос....

**Comment by penguin138** [comment]
Я сделала вот что:
Поменяла файл ./sh/recognize.sh, чтобы он выглядел вот так:
```
#! /usr/bin/env bash

source "./sh/env.sh"
python3 -m recognize --host stt.tinkoff.ru --port 443 \
    --api_key $STT_TEST_API_KEY --secret_key $STT_TEST_SECRET_KEY \
    --rate 8000 --num_channels 1 --encoding LINEAR16 --audio_file $1

```
Потом запустила `./sh/recognize.sh example.raw`
Получился вот такой выход:
```
Adding :/Users/nastya/repos/tinkoff-speech-api-examples/python to PYTHONPATH
Channel 0
Phrase start 0s
Phrase end 15s
Transcription алло а я приезжая мне уже звонили насчет этого вета месяц назад я сказал игру ребят я тут не решаю ничего квартирантка так что я говорю мне тоже где то месяц назад звонили и сказали что предложили тоже самое говорят
Confidence -131.0970458984375
----------------------------
Channel 0
Phrase start 15s
Phrase end 19.170s
Transcription там есть хозяйка что она хочет что она и делает я тут не причем
Confidence -39.85369110107422
----------------------------
```
Если еще запринтать RecognitionConfig, то получается вот такой:
```
config {
  encoding: LINEAR16
  sample_rate_hertz: 8000
  language_code: "ru-RU"
  max_alternatives: 1
  num_channels: 1
  do_not_perform_vad: false
}
```

**Comment by penguin138** [comment]
А, я не заметила тестовый скрипт. Сейчас посмотрю.

**Comment by penguin138** [comment]
Я заметила, что первое аудио, которое в том же репо лежит (audio.raw), оно тем скриптом не полностью распознается. Если убрать sttService.emit('shutdown');  и  process.exit(0); когда закончили читать аудио, то оно отправляет все ответы. Нужно правильным образом видимо синхронизировать читателя и писателя, но я не шарю в node js. Проблема со вторым аудио этим не решается(

**Comment by subnetsRU** [comment]
>Получился вот такой выход

Поставил ожидание результатов 2 минуты, но мой результат не поменялся:
```
# time node talk.js 1545057637.659053.raw
{ streaming_config:
   { config:
      { encoding: 'LINEAR16',
        sample_rate_hertz: 8000,
        language_code: 'ru-RU',
        max_alternatives: 1,
        num_channels: 1 } } }
[05.08.2019 10:36:29] sttService connected
[05.08.2019 10:36:29] File read ended
[05.08.2019 10:38:29] Done

real	2m0,943s
```
Висел и ничего так и не выдал. Файлы одинаковые, конфиги одинаковые, а результат разный... Магия... :(((

>оно тем скриптом не полностью распознается

Они синхронизированы. Читатель читает 320 байт и  только после это писатель пишет прочтенные 320 байт в sttService.

Просто когда читатель закончил читать (файл кончился), то он не особо ждет результатов, задержка в 15 сек. перед выходом. Это ж просто пример, а не боевой скрипт для копипаста ;)

**Comment by subnetsRU** [comment]
Запустил tinkoff speech api в боевом варианте. Все работает. Разбираться с магией нет ни сил ни времени.

Большое спасибо за комментарии и помощь.
