### ISSUE TITLE
Question: Text-To-Speech (TTS)

### ISSUE THREAD

**Issue by subnetsRU** [TinkoffCreditSystems/tinkoff-speech-api-examples#9]
Is there a possibility of speech generation (TTS) ? Any examples ?

**Comment by penguin138** [comment]
Yes, our api supports speech synthesis. We'll be adding documentation and examples on speech synthesis soon.  For now there is only python/apis/tts.proto file that describes our synthesis api.

**Comment by subnetsRU** [comment]
Ok, will wait for the docs.

**Comment by subnetsRU** [comment]
Похоже без документации или хоть какого-то примера я не осилю... Как ни кручу упираюсь в ошибку.

Насколько я понял name в:
```
message VoiceSelectionParams {
    string language_code = 1;
    string name = 2;
    SsmlVoiceGender ssml_gender = 3;
}
```
Это одно из значений которые возвращает ListVoicesResponses. Я правильно понял ?

Соответственно пытаюсь выполнить ListVoicesRequest:
```
service TextToSpeech {
    rpc ListVoices(ListVoicesRequest)
...skiped...
message ListVoicesRequest {
    string language_code = 1;
}
```
Запрос:
```
config = {
    tinkoff: {
        host: 'tts.tinkoff.ru',
        port: '443',
    }
}
var ListVoicesRequest = {
   language_code: "ru-RU",
}
var ttsProto = grpc.loadPackageDefinition(packageDefinition).tinkoff.cloud.tts.v1;
var sslCreds = grpc.credentials.createSsl();
var client = new ttsProto.TextToSpeech(config.tinkoff.host + ':' + config.tinkoff.port, sslCreds);
var ttsService = client.ListVoices(ListVoicesRequest);
```
И сразу получаю:
```
node_modules/grpc/src/client.js:480
    throw new Error('Argument mismatch in makeUnaryRequest');
```
Скорее всего я что-то делаю не так. Но вот что... гугление в тупике...

Буду рад любому совету.

**Comment by subnetsRU** [comment]
Оказывается ошибка вылезала из-за того, callback в makeUnaryRequest был в undefined, он ожидает function.

Если добавить в client.ListVoices три аргумента:
```
var ttsService = client.ListVoices(ListVoicesRequest,metadata,function(data){console.log('client.ListVoices data',data);});
```
То выдает ошибку:
```
Error: 7 PERMISSION_DENIED: RPC failed with status PERMISSION_DENIED: tinkoff.cloud.tts.v1.TextToSpeech/ListVoices is not allowed for audience tinkoff.cloud.stt.
```
Если в auth_payload заменить значение aud с tinkoff.cloud.stt на tinkoff.cloud.tts, то ошибка:
```
Error: 7 PERMISSION_DENIED: RPC failed with status PERMISSION_DENIED: tinkoff.cloud.tts is not allowed for API_KEY ТУТ_API_КЛЮЧ. Allowed scopes: tinkoff.cloud.stt
```
Подскажите, а что для TTS нужно получать отдельную пару API_KEY и SECRET_KEY ?

**Comment by standy66** [comment]
Нужен API-ключ, который содержит префикс "tinkoff.cloud.tts.v1.TextToSpeech" у себя в allowed scopes. Публичный синтез речи пока в альфе, поэтому мы не выдаём на него доступ по-умолчанию. Напишите нам на speech@tinkoff.ru за подробностями.

**Comment by subnetsRU** [comment]
Спасибо, написал, жду ответа.

**Comment by standy66** [comment]
Примеры с синтезом добавлены в репозиторий.
